stages:
  - test
  # - package
  # - test_deployment
  # - productive_deployment
  # - notification

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  ROOT: vts_sqflite

test:
  image: $FLUTTER_IMAGE
  stage: test
  before_script:
    - cd $ROOT
  script:
    - flutter test --coverage
    - genhtml lcov.info --output=coverage
  artifacts:
    expire_in: 5 days
