name: sqflite_common_test
description: SQFlite test package
version: 0.4.0-nullsafety.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  vts_sqflite_common_ffi:
  vts_sqflite_common:
  test:
  path:
  synchronized:
dev_dependencies:
  process_run: '>=0.11.0+2'

  lints: '>=1.0.1'

dependency_overrides:
  vts_sqflite_common:
    path: ../vts_sqflite_common
  vts_sqflite_common_ffi:
    path: ../vts_sqflite_common_ffi
