name: sqflite_common_test
description: SQFlite test package
version: 0.4.0-nullsafety.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sqflite_common_ffi: '>=2.2.0-dev.5 <4.0.0'
  vts_sqflite_common: '>=2.4.0-dev.5 <4.0.0'
  test:
  path:
  synchronized:
dev_dependencies:
  process_run: '>=0.11.0+2'

  lints: '>=1.0.1'

dependency_overrides:
  vts_sqflite_common:
    path: ../vts_sqflite_common
  sqflite_common_ffi:
    path: ../sqflite_common_ffi
