stages:
  - test-demo
  - package-demo
  # - test_deployment
  # - productive_deployment
  # - notification

variables:
  ROOT: vts_sqflite/example

.base:
  before_script:
    - cd $ROOT

test-demo:
  image: $FLUTTER_IMAGE
  stage: test-demo
  extends: .base
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - $ROOT/coverage/
    expire_in: 5 days

build_android_demo:
  stage: package-demo
  image: $FLUTTER_IMAGE
  extends: .base
#   extends: .android_key_store
  script: flutter build apk --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - $ROOT/build/app/outputs/apk/release/app-release.apk
    expire_in: 1 day

build_ios_demo:
  stage: package-demo
  image: $FLUTTER_IMAGE
  extends: .base
  script:
    # although fastlane also is capable of building the ipa, we are doing it with flutter to ensure it has the same versioning like the Android app
    - flutter build ios --release --build-number=$CI_PIPELINE_ID
  artifacts:
    untracked: true
    expire_in: 1 day
  tags:
    - ios
#   only:
#     - master
