stages:
  - test
  # - package
  # - test_deployment
  # - productive_deployment
  # - notification

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  ROOT: vts_sqflite/example

test:
  image: $FLUTTER_IMAGE
  stage: test
  before_script:
    - cd $ROOT
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - $ROOT/coverage/
    expire_in: 5 days

build_android:
  stage: package
  image: $FLUTTER_IMAGE
#   extends: .android_key_store
  script: flutter build apk --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - $ROOT/app/outputs/apk/release/app-release.apk
    expire_in: 1 day

build_ios:
  stage: package
  image: $FLUTTER_IMAGE
  script:
    # although fastlane also is capable of building the ipa, we are doing it with flutter to ensure it has the same versioning like the Android app
    - flutter build ios --release --build-number=$CI_PIPELINE_ID
  artifacts:
    untracked: true
    expire_in: 1 day
  tags:
    - ios
#   only:
#     - master
