name: vts_sqflite_common_ffi
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi
description: sqflite ffi based implementation, for desktop and units tests.
version: 2.2.0+1
funding:
  - https://github.com/sponsors/alextekartik

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  sqlite3: '>=1.9.1 <3.0.0'
  vts_sqflite_common:
  synchronized: '>=3.0.0 <5.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  lints:
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  pub_semver: '>=2.0.0'
  archive:
  http:

dependency_overrides:
  vts_sqflite_common:
    path: ../vts_sqflite_common

